# Generated by Django 3.2.12 on 2022-04-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='дата события')),
                ('views', models.PositiveIntegerField(blank=True, verbose_name='количество показов')),
                ('clicks', models.PositiveIntegerField(blank=True, verbose_name='количество кликов')),
                ('cost', models.FloatField(blank=True, verbose_name='стоимость кликов')),
            ],
        ),
    ]
