# Generated by Django 3.2.12 on 2022-04-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='clicks',
            field=models.IntegerField(blank=True, verbose_name='количество кликов'),
        ),
    ]
